spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:9000
      filter:
        enabled: false
  application:
    name: provider
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
rocketmq:
  name-server: 120.48.83.127:9876
  producer:
    group: myprovider